### ISSUE TITLE
Navigation functionality

### ISSUE THREAD

**Issue by GordiArtur** [GordiArtur/amir-blog#10]
Implement navigation functionality

**Comment by GordiArtur** [comment]
Current plan:

Left menu (in order):
- Blog title: link to home page

Middle menu (in order)
- Home: link to home page
- Categories: dropdown links to categories
- About: link to about page
- Write a post (if signed in and allowed to post): link to write a post page

Right menu (in order)
- Login/Logout: link to google authentication
- Search: link/popup to search

**Comment by adaneshv** [comment]
Looks great to me, for the middle menu I would also add "Contact" after "About": 

Contact: links to the page with contact information (where they can access a direct textbox for contacting the admin as well as information regarding how else they can contact; email & social media links) 

As for the specific dropdown links under categories, I haven't decided what will be put there. Currently thinking of categories such as "Education", "Psychology", "Sports", "Music", "Entertainment", etc. but even those are not definite yet.

**Comment by GordiArtur** [comment]
Implemented in https://github.com/GordiArtur/amir-blog/pull/27

> As for the specific dropdown links under categories, I haven't decided what will be put there. Currently thinking of categories such as "Education", "Psychology", "Sports", "Music", "Entertainment", etc. but even those are not definite yet.

The specific categories will be added in https://github.com/GordiArtur/amir-blog/issues/20
